/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InteriorGUI;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Arvy Enriquez
 */
public class FoodShop extends javax.swing.JFrame {

    /**
     * Creates new form FoodShop
     */
    int money = 0;
    int hunger = 0;
    int stamina = 0;
    String acc = "";
    public FoodShop() {
        initComponents();
        File file_temp = new File("db/temp.txt");
        String acc1 = "";
        try {
            FileReader fr = new FileReader(file_temp);
            BufferedReader br = new BufferedReader(fr);
            String data;
            String dat;
            while ((data = br.readLine()) != null) {
                dat = data;
                acc1 = dat;
            }
        } catch (FileNotFoundException ex) {

        } catch (IOException ex) {

        }
        String[] inf = acc1.split(",");
        hunger = Integer.parseInt(inf[4]);
        money = Integer.parseInt(inf[5]);
        stamina = Integer.parseInt(inf[3]);
        acc = inf[0];
        updateMoney();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        staminaBar = new javax.swing.JProgressBar();
        hungerBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Go Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Jokerman", 0, 16)); // NOI18N
        jLabel2.setText("Account:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 305, -1, -1));

        jLabel4.setFont(new java.awt.Font("Jokerman", 0, 16)); // NOI18N
        jLabel4.setText("Money:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        jButton2.setText("Eat for 25 Coins");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 150, -1));

        jButton1.setText("Eat for 5 Coins");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 150, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blookat-hppack.gif"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 28, 30, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/candy3.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 7, 30, 20));

        staminaBar.setToolTipText("Stamina Bar");
        jPanel1.add(staminaBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 120, -1));

        hungerBar.setToolTipText("Hunger Bar");
        jPanel1.add(hungerBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 120, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/foodasd.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*if (money >= 5) {
             money -= 5;
             hunger += 2;
             updateMoney2();
        } else {
             JOptionPane.showMessageDialog(this, "You don't have enough balance money!");
        }*/
        boolean entry = true;
        if ((hunger + 5) > 100) {
            entry = false;
            JOptionPane.showMessageDialog(this, "Your pet is already full!");
        } else if (money < 5) {
            entry = false;
            JOptionPane.showMessageDialog(this, "You don't have enough balance money!");
        }
        if (entry == true) {
            money -= 5;
            hunger += 5;
            updateMoney2();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean entry = true;
        if ((hunger + 25) > 100) {
            entry = false;
            JOptionPane.showMessageDialog(this, "Your pet is already full!");
        } else if (money < 25) {
            entry = false;
            JOptionPane.showMessageDialog(this, "You don't have enough balance money!");
        }
        if (entry == true) {
            money -= 25;
            hunger += 25;
            updateMoney2();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new MainMap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    public void updateMoney2() {
        String self_user = acc.split(",")[0];
        File file_temp = new File("db/temp.txt");
        File file = new File("db/players.txt");
        
        ArrayList<String> userList = new ArrayList();
        String dat_change = "";
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            String data;
            String dat;
            while ((data = br.readLine()) != null) {
                dat = data;
                String [] datarr = dat.split(",");
                if (self_user.equals(datarr[0])) {
                    dat_change = dat;
                } else {
                    userList.add(data);
                }
            }
            String[] first = dat_change.split(",");
            String recipient = first[0] + "," + first[1] + "," + first[2] + "," + first[3] + "," +  hunger + "," + money + "," + first[6] + "," + first[7] + "," + first[8];
            try (PrintWriter pw = new PrintWriter(new FileWriter(file, false))) {
                userList.forEach((user) -> {
                    pw.println(user.toString());
                });
            } catch (IOException ex) {
            }
            try (PrintWriter pw = new PrintWriter(new FileWriter(file, true))) {
                pw.println(recipient);
            } catch (IOException ex) {
            }
            try (PrintWriter pw = new PrintWriter(new FileWriter(file_temp, true))) {
                pw.println(recipient);
            } catch (IOException ex) {
            }
            JOptionPane.showMessageDialog(this, "Your pet has eaten successfully!");
        } catch (FileNotFoundException ex) {

        } catch (IOException ex) {

        }
        
        updateMoney();
    }
    
    public void updateMoney() {
        jLabel2.setText("Money: " + money);
        jLabel4.setText("Account: " + acc);
        hungerBar.setValue(hunger);
        staminaBar.setValue(stamina);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodShop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar hungerBar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar staminaBar;
    // End of variables declaration//GEN-END:variables
}
