/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InteriorGUI;

import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Arvy Enriquez
 */
public class House extends javax.swing.JFrame {

    /**
     * Creates new form House
     */
    public House() {
        initComponents();
        getData();
    }
    String name = "";
    int mney = 0;
    int fd1 = 0;
    int fd2 = 0;
    int stmna = 0;
    int hnger = 0;
    int character = 0;
    public void getData() {
        File file_temp = new File("db/temp.txt");
        File file_player = new File("db/players.txt");
        String acc = "";
        try {
            FileReader fr = new FileReader(file_temp);
            BufferedReader br = new BufferedReader(fr);
            String data;
            String dat;
            while ((data = br.readLine()) != null) {
                dat = data;
                String [] datarr = dat.split(",");
                acc = dat;
            }
        } catch (FileNotFoundException ex) {

        } catch (IOException ex) {

        }
        String[] inf = acc.split(",");
        fd1 = Integer.parseInt(inf[7]);
        fd2 = Integer.parseInt(inf[8]);
        stmna = Integer.parseInt(inf[3]);
        hnger = Integer.parseInt(inf[4]);
        character = Integer.parseInt(inf[2]);
        name = inf[0];
        mney = Integer.parseInt(inf[5]);
        accountName.setText(name);
        moneyText.setText(mney + "");
        hungerBar.setValue(hnger);
        staminaBar.setValue(stmna);
        if (character == 1) {
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1st char.png")));
        } else if (character == 2) {
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/2nd char.png")));
        } else if (character == 3) {
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/3rd char.png")));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hungerBar = new javax.swing.JProgressBar();
        staminaBar = new javax.swing.JProgressBar();
        accountName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        moneyText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 300, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/candy3.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 7, 30, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blookat-hppack.gif"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 28, 30, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tap to rest");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 220, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tv_normal.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel7MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        hungerBar.setToolTipText("Hunger Bar");
        jPanel1.add(hungerBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 120, -1));

        staminaBar.setToolTipText("Stamina Bar");
        jPanel1.add(staminaBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 120, -1));

        accountName.setFont(new java.awt.Font("Jokerman", 0, 18)); // NOI18N
        accountName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(accountName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 5, 370, 30));

        jLabel4.setFont(new java.awt.Font("Jokerman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Account:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, -1));

        jLabel5.setFont(new java.awt.Font("Jokerman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Money:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        moneyText.setFont(new java.awt.Font("Jokerman", 0, 18)); // NOI18N
        moneyText.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(moneyText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 210, 30));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 210, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home00.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseReleased
        String self_user = name;
        File file_temp = new File("db/temp.txt");
        File file = new File("db/players.txt");
        
        ArrayList<String> userList = new ArrayList();
        String dat_change = "";
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            String data;
            String dat;
            while ((data = br.readLine()) != null) {
                dat = data;
                String [] datarr = dat.split(",");
                if (self_user.equals(datarr[0])) {
                    dat_change = dat;
                } else {
                    userList.add(data);
                }
            }
            String[] first = dat_change.split(",");
            boolean tray = true;
            if ((stmna + 10) > 100) {
                tray = false;
                JOptionPane.showMessageDialog(this, "Your pet is well rested!");
            } else if ((hnger - 10) < 0) {
                tray = false;
                JOptionPane.showMessageDialog(this, "Your pet is hungry!");
            }
            if (tray == true) {
                stmna += 10;
                hnger -= 10;
                String recipient = first[0] + "," + first[1] + "," + first[2] + "," + stmna + "," +  hnger + "," + first[5] + "," + first[6] + "," + first[7] + "," + first[8];
                try (PrintWriter pw = new PrintWriter(new FileWriter(file, false))) {
                    userList.forEach((user) -> {
                        pw.println(user.toString());
                    });
                } catch (IOException ex) {
                }
                try (PrintWriter pw = new PrintWriter(new FileWriter(file, true))) {
                    pw.println(recipient);
                } catch (IOException ex) {
                }
                try (PrintWriter pw = new PrintWriter(new FileWriter(file_temp, true))) {
                    pw.println(recipient);
                } catch (IOException ex) {
                }
                JOptionPane.showMessageDialog(this, "Success!");
            }
        } catch (FileNotFoundException ex) {

        } catch (IOException ex) {

        }
        
        updateText();
    }//GEN-LAST:event_jLabel7MouseReleased

    public void updateText() {
        accountName.setText(name);
        moneyText.setText(mney + "");
        hungerBar.setValue(hnger);
        staminaBar.setValue(stmna);
        if (character == 1) {
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1st char.png")));
        } else if (character == 2) {
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/2nd char.png")));
        } else if (character == 3) {
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/3rd char.png")));
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new MainMap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tv_alpha.png")));
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tv_normal.png")));
    }//GEN-LAST:event_jLabel7MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(House.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(House.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(House.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(House.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new House().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountName;
    private javax.swing.JProgressBar hungerBar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel moneyText;
    private javax.swing.JProgressBar staminaBar;
    // End of variables declaration//GEN-END:variables
}
