/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InteriorGUI;

/**
 *
 * @author Arvy Enriquez
 */
import com.sun.glass.events.KeyEvent;
import java.io.*;
import javax.swing.*;

public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group1 = new javax.swing.ButtonGroup();
        characterGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        character1 = new javax.swing.JRadioButton();
        character2 = new javax.swing.JRadioButton();
        character3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        Register = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        characterName = new javax.swing.JTextField();
        maleButton = new javax.swing.JRadioButton();
        femaleButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        characterGroup.add(character1);
        character1.setText("Chicken");
        character1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                character1ActionPerformed(evt);
            }
        });
        jPanel1.add(character1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        characterGroup.add(character2);
        character2.setText("Crocodile");
        jPanel1.add(character2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        characterGroup.add(character3);
        character3.setText("Dog");
        jPanel1.add(character3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Register");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        Register.setBackground(new java.awt.Color(204, 255, 255));
        Register.setText("Register");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        jPanel1.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 130, 40));

        Back.setBackground(new java.awt.Color(204, 255, 255));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 130, 40));

        characterName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                characterNameKeyTyped(evt);
            }
        });
        jPanel1.add(characterName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 190, -1));

        group1.add(maleButton);
        maleButton.setText("Male");
        jPanel1.add(maleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        group1.add(femaleButton);
        femaleButton.setText("Female");
        jPanel1.add(femaleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Character Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gender:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Character:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/3rd char.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel8MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, 180));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1st char.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel9MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 180));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/2nd char.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel10MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, 180));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Homepage.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        JFrame F = new JFrame();
        String username = characterName.getText().replace(",", "-");
        String gender = "";
        if (maleButton.isSelected()){
            gender = "Male";
        } else if (femaleButton.isSelected()){
            gender = "Female";
        }
        int character = 0;
        if (character1.isSelected()) {
            character = 1;
        } else if (character2.isSelected()) {
            character = 2;
        } else if (character3.isSelected()) {
            character = 3;
        }
        File file = new File("db/players.txt");
        File files = new File("db/temp.txt");
        boolean allowed = true;
        boolean enter = true;
        if (characterName.getText().trim().isEmpty()) {
            enter = false;
            JOptionPane.showMessageDialog(F, "Please Enter a Username!");
        } else if (characterName.getText().contains(",")) {
            enter = false;
            JOptionPane.showMessageDialog(F, "Don't use comma (,)!");
        } else if (gender.equals("")) {
            enter = false;
            JOptionPane.showMessageDialog(F, "Please Choose a Gender!");
        } else if (character == 0) {
            enter = false;
            JOptionPane.showMessageDialog(F, "Please Choose a Character!");
        }
        if (enter == true) {
            try {
                FileReader fr = new FileReader(file);
                BufferedReader br = new BufferedReader(fr);
                String data;
                String dat;
                String[] lastlist = {};
                while ((data = br.readLine()) != null) {
                    dat = data;
                    String [] datarr = dat.split(",");
                    if (username.equals(datarr[0])) {
                        allowed = false;
                        break;
                    }
                }
            } catch (FileNotFoundException ex) {

            } catch (IOException ex) {

            }
            //              USERNAME         GENDER         CHARACTER         Stamina    HUNGER      MONEY       BNK MNY    FD1 FD2
            String finale = username + "," + gender + "," + character + "," + 100 + "," +  100 + "," + 1000 + "," + 500 + "," + 1 + "," + 1;
            if (allowed == true) {
                try (PrintWriter pw = new PrintWriter(new FileWriter(file, true))){
                    pw.println(finale);
                } catch (IOException ex) {

                }
                try (PrintWriter pw = new PrintWriter(new FileWriter(files, true))){
                    pw.println(finale);
                } catch (IOException ex) {

                }
                JOptionPane.showMessageDialog(F, "Success!");
                new Home().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(F, "Username Already Exist!");
            }
        }
    }//GEN-LAST:event_RegisterActionPerformed

    private void character1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_character1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_character1ActionPerformed

    private void jLabel8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseReleased
        character3.setSelected(true);
    }//GEN-LAST:event_jLabel8MouseReleased

    private void jLabel10MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseReleased
        character2.setSelected(true);
    }//GEN-LAST:event_jLabel10MouseReleased

    private void jLabel9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseReleased
        character1.setSelected(true);
    }//GEN-LAST:event_jLabel9MouseReleased

    private void characterNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_characterNameKeyTyped
        char vchar = evt.getKeyChar();
        if (characterName.getText().length() > 30){
            evt.consume();
        }
    }//GEN-LAST:event_characterNameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Register;
    private javax.swing.JLabel background;
    private javax.swing.JRadioButton character1;
    private javax.swing.JRadioButton character2;
    private javax.swing.JRadioButton character3;
    private javax.swing.ButtonGroup characterGroup;
    private javax.swing.JTextField characterName;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.ButtonGroup group1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton maleButton;
    // End of variables declaration//GEN-END:variables
}
