/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InteriorGUI;

import com.sun.glass.events.KeyEvent;
import java.io.*;
import javax.swing.*;
import java.util.*;

/**
 *
 * @author Arvy Enriquez
 */
public class Stadium extends javax.swing.JFrame {

    /**
     * Creates new form Stadium
     */
    public Stadium() {
        initComponents();
        hideContainers();
        SpinnerModel model = new SpinnerNumberModel(1, 1, 10, 1);
        jSpinner1.setModel(model);
        JSpinner spin = new JSpinner();
        JFormattedTextField tf = ((JSpinner.DefaultEditor)jSpinner1.getEditor()).getTextField();
        tf.setEditable(false);
        betGame.setVisible(true);
        getData();
    }
    String access_acc = "";
    public void getData() {
        File file_temp = new File("db/temp.txt");
        File file_player = new File("db/players.txt");
        String acc = "";
        try {
            FileReader fr = new FileReader(file_temp);
            BufferedReader br = new BufferedReader(fr);
            String data;
            String dat;
            while ((data = br.readLine()) != null) {
                dat = data;
                String [] datarr = dat.split(",");
                acc = dat;
            }
        } catch (FileNotFoundException ex) {

        } catch (IOException ex) {

        }
        String[] inf = acc.split(",");
        money = Integer.parseInt(inf[5]);
        access_acc = inf[0];
        stamina = Integer.parseInt(inf[3]);
        hunger = Integer.parseInt(inf[4]);
        System.out.println(inf[3]);
        setMoney(0);
    }
    int hunger = 0;
    int money = 0;
    int stamina = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        hungerBar = new javax.swing.JProgressBar();
        staminaBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        rpsButton = new javax.swing.JButton();
        betGameButton = new javax.swing.JButton();
        tosscoinButton = new javax.swing.JButton();
        betGame = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        moneyText1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tossCoin = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        moneyText2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        rps = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        moneyText = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blookat-hppack.gif"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 27, 30, 20));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/candy3.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 8, 30, 20));

        hungerBar.setToolTipText("Hunger Bar");
        jPanel1.add(hungerBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 120, -1));

        staminaBar.setToolTipText("Stamina Bar");
        jPanel1.add(staminaBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 120, -1));

        jLabel1.setFont(new java.awt.Font("AR CENA", 1, 36)); // NOI18N
        jLabel1.setText("Welcome to Stadium");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        rpsButton.setBackground(new java.awt.Color(204, 255, 255));
        rpsButton.setText("Jack n Poy");
        rpsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpsButtonActionPerformed(evt);
            }
        });
        jPanel1.add(rpsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 130, -1, -1));

        betGameButton.setBackground(new java.awt.Color(204, 255, 255));
        betGameButton.setText("Bet Game");
        betGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betGameButtonActionPerformed(evt);
            }
        });
        jPanel1.add(betGameButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        tosscoinButton.setBackground(new java.awt.Color(204, 255, 255));
        tosscoinButton.setText("Toss Coin");
        tosscoinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tosscoinButtonActionPerformed(evt);
            }
        });
        jPanel1.add(tosscoinButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        betGame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setText("Start");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        betGame.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 180, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Horse Racing Bet Game");
        betGame.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        betGame.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 210, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Pick Horse Number");
        betGame.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 210, -1));
        betGame.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 80, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Place Bet Here!");
        betGame.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 210, -1));

        jLabel11.setFont(new java.awt.Font("Jokerman", 1, 16)); // NOI18N
        jLabel11.setText("Money:");
        betGame.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        moneyText1.setFont(new java.awt.Font("Jokerman", 1, 16)); // NOI18N
        betGame.add(moneyText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 210, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stadium321.png"))); // NOI18N
        jLabel17.setText("jLabel15");
        betGame.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(-23, -115, 710, -1));

        jPanel1.add(betGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 690, 280));

        tossCoin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Place Bet Here!");
        tossCoin.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 210, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Or");
        tossCoin.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        moneyText2.setFont(new java.awt.Font("Jokerman", 1, 16)); // NOI18N
        tossCoin.add(moneyText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 210, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Coin Toss!");
        tossCoin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 670, 50));

        jButton8.setText("Tails");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        tossCoin.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, 40));

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        tossCoin.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 210, 40));

        jButton9.setText("Heads");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        tossCoin.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, 40));

        jLabel12.setFont(new java.awt.Font("Jokerman", 1, 16)); // NOI18N
        jLabel12.setText("Money:");
        tossCoin.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stadium321.png"))); // NOI18N
        jLabel15.setText("jLabel15");
        tossCoin.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-23, -115, 710, -1));

        jPanel1.add(tossCoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 690, 280));

        rps.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" Free Entry!");
        rps.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton4.setText("Scissors");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        rps.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 150, 50));

        jButton5.setText("Paper");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        rps.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 150, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Or");
        rps.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Rock, Paper or Scissors!");
        rps.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 690, 50));

        jButton10.setText("Rock");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        rps.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 150, 50));

        moneyText.setFont(new java.awt.Font("Jokerman", 1, 16)); // NOI18N
        rps.add(moneyText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 210, 30));

        jLabel10.setFont(new java.awt.Font("Jokerman", 1, 16)); // NOI18N
        jLabel10.setText("Money:");
        rps.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stadium321.png"))); // NOI18N
        jLabel16.setText("jLabel15");
        rps.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-23, -115, 710, -1));

        jPanel1.add(rps, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 690, 280));

        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 100, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stadium123.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 720, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rpsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpsButtonActionPerformed
        hideContainers();
        rps.setVisible(true);
    }//GEN-LAST:event_rpsButtonActionPerformed

    private void betGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betGameButtonActionPerformed
        hideContainers();
        betGame.setVisible(true);
    }//GEN-LAST:event_betGameButtonActionPerformed

    private void tosscoinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tosscoinButtonActionPerformed
        hideContainers();
        tossCoin.setVisible(true);
    }//GEN-LAST:event_tosscoinButtonActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
            if (!(jTextField3.getText().isEmpty()) && Integer.parseInt(jTextField3.getText()) > 0) {
                playCoinToss(0);
            } else {
                JOptionPane.showMessageDialog(this, "Invalid amount!");
            }
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            if (!(jTextField3.getText().isEmpty()) && Integer.parseInt(jTextField3.getText()) > 0) {
                playCoinToss(1);
            } else {
                JOptionPane.showMessageDialog(this, "Invalid amount!");
            }
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACKSPACE) || (vchar == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar)) || (vchar == KeyEvent.VK_BACKSPACE) || (vchar == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            if (!(jTextField2.getText().isEmpty()) && Integer.parseInt(jTextField2.getText()) > 0) {
                playBetGame();
            } else {
                JOptionPane.showMessageDialog(this, "Invalid amount!");
            }
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        playRPS(0);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        playRPS(1);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        playRPS(2);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new MainMap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    public void hideContainers() {
        tossCoin.setVisible(false);
        betGame.setVisible(false);
        rps.setVisible(false);
    }
    public void playBetGame() {
        if (stamina > 5) {
            int bet = Integer.parseInt(jTextField2.getText());
            if (bet <= money) {
                int horse = (int) (Math.random() * 10) + 1;
                if (horse == Integer.parseInt(jSpinner1.getValue().toString())) {
                    JOptionPane.showMessageDialog(this, "Your horse won Win!");
                    money += bet*10;
                } else {
                    JOptionPane.showMessageDialog(this, "You Lose! Horse " + horse + " won");
                    money -= bet;
                }
            } else {
                JOptionPane.showMessageDialog(this, "You don't have enough money!");
            }
            setMoney(5);
        } else {
            JOptionPane.showMessageDialog(this, "You don't have enough stamina!");
        }
    }
    public void playCoinToss(int code) {
        if (stamina >= 5) {
            int bet = Integer.parseInt(jTextField3.getText());
            if (bet <= money) {
                int rps = (int) (Math.random() * 2);
                if (rps == code) {
                    JOptionPane.showMessageDialog(this, "Win!");
                    money += bet*2;
                } else {
                    JOptionPane.showMessageDialog(this, "Lose!");
                    money -= bet;
                }
            } else {
                JOptionPane.showMessageDialog(this, "You don't have enough money!");
            }
            setMoney(5);
        } else {
            JOptionPane.showMessageDialog(this, "Your pet don't have enough stamina!");
        }
    }
    public void playRPS(int code) {
        if (stamina >= 1) {
            int z = (int) (Math.random() * 3) + 1;
            switch (code) {
                case 0:
                    if (z == 1) {
                        JOptionPane.showMessageDialog(this, "You: Rock\nComputer: Rock" + "\nResult: Tie!");
                    } else if (z == 2) {
                        JOptionPane.showMessageDialog(this, "You: Rock\nComputer: Paper" + "\nResult: Lose!");
                    } else if (z == 3) {
                        JOptionPane.showMessageDialog(this, "You: Rock\nComputer: Scissors" + "\nResult: Win!");
                        money += 20;
                    }
                break;
                case 1:
                    if (z == 1) {
                        JOptionPane.showMessageDialog(this, "You: Paper\nComputer: Rock" + "\nResult: Win!");
                        money += 20;
                    } else if (z == 2) {
                        JOptionPane.showMessageDialog(this, "You: Paper\nComputer: Paper" + "\nResult: Tie!");
                    } else if (z == 3) {
                        JOptionPane.showMessageDialog(this, "You: Paper\nComputer: Scissors" + "\nResult: Lose!");
                    }
                break;
                case 2:
                    if (z == 1) {
                        JOptionPane.showMessageDialog(this, "You: Scissors\nComputer: Rock" + "\nResult: Lose!");
                    } else if (z == 2) {
                        JOptionPane.showMessageDialog(this, "You: Scissors\nComputer: Paper" + "\nResult: Win!");
                        money += 20;
                    } else if (z == 3) {
                        JOptionPane.showMessageDialog(this, "You: Scissors\nComputer: Scissors" + "\nResult: Tie!");
                    }
                break;
            }
            setMoney(1);
        } else {
            JOptionPane.showMessageDialog(this, "You don't have enough stamina!");
        }
    }
    public void setMoney(int stam) {
        String search_id = access_acc;
        File file_temp = new File("db/temp.txt");
        File file = new File("db/players.txt");
        ArrayList<String> userList = new ArrayList();
        String dat_change = "";
        try {
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            String data;
            String dat;
            while ((data = br.readLine()) != null) {
                dat = data;
                String [] datarr = dat.split(",");
                if (search_id.equals(datarr[0])) {
                    dat_change = dat;
                } else {
                    userList.add(data);
                }
            }
            String[] info = dat_change.split(",");
            stamina -= stam;
            String userr = info[0] + "," + info[1] + "," + info[2] + "," + stamina + "," +  info[4] + "," + money + "," + info[6] + "," + info[7] + "," + info[8];
            try (PrintWriter pw = new PrintWriter(new FileWriter(file, false))) {
                userList.forEach((user) -> {
                    pw.println(user.toString());
                });
            } catch (IOException ex) {
            }
            try (PrintWriter pw = new PrintWriter(new FileWriter(file, true))) {
                pw.println(userr);
            } catch (IOException ex) {
            }
            try (PrintWriter pw = new PrintWriter(new FileWriter(file_temp, true))) {
                pw.println(userr);
            } catch (IOException ex) {
            }
        } catch (FileNotFoundException ex) {

        } catch (IOException ex) {

        }
        hungerBar.setValue(hunger);
        staminaBar.setValue(stamina);
        moneyText.setText(money + "");
        moneyText1.setText(money + "");
        moneyText2.setText(money + "");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stadium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stadium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stadium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stadium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stadium().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel betGame;
    private javax.swing.JButton betGameButton;
    private javax.swing.JProgressBar hungerBar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel moneyText;
    private javax.swing.JLabel moneyText1;
    private javax.swing.JLabel moneyText2;
    private javax.swing.JPanel rps;
    private javax.swing.JButton rpsButton;
    private javax.swing.JProgressBar staminaBar;
    private javax.swing.JPanel tossCoin;
    private javax.swing.JButton tosscoinButton;
    // End of variables declaration//GEN-END:variables
}
